version: '3.6'

services:
  spy-app:
    env_file: .env
    container_name: spy-app
    image: ghcr.io/amiralitaheri/spy
    restart: always
    networks:
      main_network:
        ipv4_address: 192.0.0.20

networks:
  main_network:
    name: main_network
    external: true
    driver: bridge